---
description: 
pack: aws_cloudhsm
enabled: true
entry_point: run.py
name: get_config
runner_type: python-script
parameters:
  action:
    default: get_config
    immutable: true
    type: string
  cls:
    default: cloudhsm
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ClientArn:
    type: string
    description: "The ARN of the client."
    required: true
  ClientVersion:
    type: string
    description: "The client version."
    required: true
  HapgList:
    type: array
    description: "A list of ARNs that identify the high-availability partition groups that are associated with the client."
    required: true