---
description: 
pack: aws_es
enabled: true
entry_point: run.py
name: describe_elasticsearch_domain_config
runner_type: python-script
parameters:
  action:
    default: describe_elasticsearch_domain_config
    immutable: true
    type: string
  cls:
    default: es
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  DomainName:
    type: string
    description: "The Elasticsearch domain that you want to get information about."
    required: true