# ENABLE THE RULE TO USE IT
name: "lmlogs_alert_rule"
pack: "logicmonitor"
description: "Maps LM Log Alerts (LML) to an action"
enabled: false

trigger:
  type: "logicmonitor.alert_trigger"

criteria:
  trigger.alertId:
    type: "contains"
    pattern: "LML"

action:
  ref: "logicmonitor.get_alert_list"
  parameters:
    payload: "{{trigger}}"

# Maps LM Log Alerts (LML) to an action

# TROUBLESHOOTING
# On the LogicMonitor side, your Stackstorm Integration’s POST payload should include the appropriate
# object (key/value pair) for your rule's criteria. Ensure the key/value pair indicated in the Rule's
# criteria section exists in the payload being sent to the webhook-sensor.
#
# The default payload object DOES NOT CONTAIN the { ... “alertId”:”##ALERTID##” ... } key/value pair.
# Therefore, you will have to add that key/value pair to your integration's POST payload.
#
# RELATED DOCUMENTATION
# https://www.logicmonitor.com/support/alerts/about-alerts/what-does-logicmonitor-alert-on
# https://www.logicmonitor.com/support/logicmodules/about-logicmodules/tokens-available-in-datasource-alert-messages
# https://docs.stackstorm.com/rules.html