---
description: 
pack: aws_s3
enabled: true
entry_point: run.py
name: get_bucket_accelerate_configuration
runner_type: python-script
parameters:
  action:
    default: get_bucket_accelerate_configuration
    immutable: true
    type: string
  cls:
    default: s3
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Bucket:
    type: string
    description: "Name of the bucket for which the accelerate configuration is retrieved."
    required: true