---
description: 
pack: aws_devicefarm
enabled: true
entry_point: run.py
name: get_account_settings
runner_type: python-script
parameters:
  action:
    default: get_account_settings
    immutable: true
    type: string
  cls:
    default: devicefarm
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string