---
description: 
pack: aws_redshift
enabled: true
entry_point: run.py
name: describe_hsm_configurations
runner_type: python-script
parameters:
  action:
    default: describe_hsm_configurations
    immutable: true
    type: string
  cls:
    default: redshift
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  HsmConfigurationIdentifier:
    type: string
    description: "The identifier of a specific Amazon Redshift HSM configuration to be described. If no identifier is specified, information is returned for all HSM configurations owned by your AWS customer account."
  MaxRecords:
    type: integer
    description: " The maximum number of response records to return in each call. If the number of remaining response records exceeds the specified MaxRecords value, a value is returned in a marker field of the response. You can retrieve the next set of records by retrying the command with the returned marker value.  Default: 100 Constraints: minimum 20, maximum 100."
  Marker:
    type: string
    description: " An optional parameter that specifies the starting point to return a set of response records. When the results of a DescribeHsmConfigurations request exceed the value specified in MaxRecords, AWS returns a value in the Marker field of the response. You can retrieve the next set of response records by providing the returned marker value in the Marker parameter and retrying the request. "
  TagKeys:
    type: array
    description: "A tag key or keys for which you want to return all matching HSM configurations that are associated with the specified key or keys. For example, suppose that you have HSM configurations that are tagged with keys called owner and environment. If you specify both of these tag keys in the request, Amazon Redshift returns a response with the HSM configurations that have either or both of these tag keys associated with them."
  TagValues:
    type: array
    description: "A tag value or values for which you want to return all matching HSM configurations that are associated with the specified tag value or values. For example, suppose that you have HSM configurations that are tagged with values called admin and test. If you specify both of these tag values in the request, Amazon Redshift returns a response with the HSM configurations that have either or both of these tag values associated with them."