---
description: 
pack: aws_apigateway
enabled: true
entry_point: run.py
name: get_deployment
runner_type: python-script
parameters:
  action:
    default: get_deployment
    immutable: true
    type: string
  cls:
    default: apigateway
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  restApiId:
    type: string
    description: "The identifier of the RestApi resource for the Deployment resource to get information about."
    required: true
  deploymentId:
    type: string
    description: "The identifier of the Deployment resource to get information about."
    required: true