---
description: 
pack: aws_sns
enabled: true
entry_point: run.py
name: delete_platform_application
runner_type: python-script
parameters:
  action:
    default: delete_platform_application
    immutable: true
    type: string
  cls:
    default: sns
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  PlatformApplicationArn:
    type: string
    description: "PlatformApplicationArn of platform application object to delete."
    required: true