---
description: 
pack: aws_sns
enabled: true
entry_point: run.py
name: list_endpoints_by_platform_application
runner_type: python-script
parameters:
  action:
    default: list_endpoints_by_platform_application
    immutable: true
    type: string
  cls:
    default: sns
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  PlatformApplicationArn:
    type: string
    description: "PlatformApplicationArn for ListEndpointsByPlatformApplicationInput action."
    required: true
  NextToken:
    type: string
    description: "NextToken string is used when calling ListEndpointsByPlatformApplication action to retrieve additional records that are available after the first page results."