---
description: 
pack: aws_discovery
enabled: true
entry_point: run.py
name: list_configurations
runner_type: python-script
parameters:
  action:
    default: list_configurations
    immutable: true
    type: string
  cls:
    default: discovery
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  configurationType:
    type: string
    description: "A valid configuration identified by the Discovery Service. "
    required: true
  filters:
    type: array
    description: "You can filter the list using a key-value format. For example:   {'key': 'serverType', 'value': 'webServer'}  You can separate these items by using logical operators. "
  maxResults:
    type: integer
    description: "The total number of items to return. The maximum value is 100."
  nextToken:
    type: string
    description: "A token to start the list. Use this token to get the next set of results."