---

url:
  description: "Foreman Url"
  type: string
  required: true

username:
  type: string
  required: true

password:
  type: string
  required: true

verify_ssl:
  type: boolean
  default: False
