---
description: 
pack: aws_elb
enabled: true
entry_point: run.py
name: configure_health_check
runner_type: python-script
parameters:
  action:
    default: configure_health_check
    immutable: true
    type: string
  cls:
    default: elb
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  LoadBalancerName:
    type: string
    description: "The name of the load balancer."
    required: true
  HealthCheck:
    type: object
    description: "The configuration information for the new health check."
    required: true