---
description: 
pack: aws_gamelift
enabled: true
entry_point: run.py
name: describe_runtime_configuration
runner_type: python-script
parameters:
  action:
    default: describe_runtime_configuration
    immutable: true
    type: string
  cls:
    default: gamelift
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  FleetId:
    type: string
    description: "Unique identifier of the fleet to get the runtime configuration for."
    required: true