---
description: 
pack: aws_autoscaling
enabled: true
entry_point: run.py
name: delete_launch_configuration
runner_type: python-script
parameters:
  action:
    default: delete_launch_configuration
    immutable: true
    type: string
  cls:
    default: autoscaling
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  LaunchConfigurationName:
    type: string
    description: "The name of the launch configuration."
    required: true