---
description: 
pack: aws_rds
enabled: true
entry_point: run.py
name: revoke_db_security_group_ingress
runner_type: python-script
parameters:
  action:
    default: revoke_db_security_group_ingress
    immutable: true
    type: string
  cls:
    default: rds
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  DBSecurityGroupName:
    type: string
    description: "The name of the DB security group to revoke ingress from."
    required: true
  CIDRIP:
    type: string
    description: " The IP range to revoke access from. Must be a valid CIDR range. If CIDRIP is specified, EC2SecurityGroupName, EC2SecurityGroupId and EC2SecurityGroupOwnerId cannot be provided. "
  EC2SecurityGroupName:
    type: string
    description: " The name of the EC2 security group to revoke access from. For VPC DB security groups, EC2SecurityGroupId must be provided. Otherwise, EC2SecurityGroupOwnerId and either EC2SecurityGroupName or EC2SecurityGroupId must be provided. "
  EC2SecurityGroupId:
    type: string
    description: " The id of the EC2 security group to revoke access from. For VPC DB security groups, EC2SecurityGroupId must be provided. Otherwise, EC2SecurityGroupOwnerId and either EC2SecurityGroupName or EC2SecurityGroupId must be provided. "
  EC2SecurityGroupOwnerId:
    type: string
    description: " The AWS Account Number of the owner of the EC2 security group specified in the EC2SecurityGroupName parameter. The AWS Access Key ID is not an acceptable value. For VPC DB security groups, EC2SecurityGroupId must be provided. Otherwise, EC2SecurityGroupOwnerId and either EC2SecurityGroupName or EC2SecurityGroupId must be provided. "