---
description: 
pack: aws_config
enabled: true
entry_point: run.py
name: delete_configuration_recorder
runner_type: python-script
parameters:
  action:
    default: delete_configuration_recorder
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ConfigurationRecorderName:
    type: string
    description: "The name of the configuration recorder to be deleted. You can retrieve the name of your configuration recorder by using the DescribeConfigurationRecorders action."
    required: true