---
description: 
pack: aws_config
enabled: true
entry_point: run.py
name: delete_config_rule
runner_type: python-script
parameters:
  action:
    default: delete_config_rule
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ConfigRuleName:
    type: string
    description: "The name of the AWS Config rule that you want to delete."
    required: true