---
description: 
pack: aws_config
enabled: true
entry_point: run.py
name: deliver_config_snapshot
runner_type: python-script
parameters:
  action:
    default: deliver_config_snapshot
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  deliveryChannelName:
    type: string
    description: "The name of the delivery channel through which the snapshot is delivered."
    required: true