---
description: 
pack: aws_config
enabled: true
entry_point: run.py
name: describe_config_rules
runner_type: python-script
parameters:
  action:
    default: describe_config_rules
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ConfigRuleNames:
    type: array
    description: "The names of the AWS Config rules for which you want details. If you do not specify any names, AWS Config returns details for all your rules."
  NextToken:
    type: string
    description: "The nextToken string returned on a previous page that you use to get the next page of results in a paginated response."