---
description: 
pack: aws_config
enabled: true
entry_point: run.py
name: describe_config_rule_evaluation_status
runner_type: python-script
parameters:
  action:
    default: describe_config_rule_evaluation_status
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ConfigRuleNames:
    type: array
    description: "The name of the AWS managed Config rules for which you want status information. If you do not specify any names, AWS Config returns status information for all AWS managed Config rules that you use. "