---
description: 
pack: aws_config
enabled: true
entry_point: run.py
name: describe_compliance_by_config_rule
runner_type: python-script
parameters:
  action:
    default: describe_compliance_by_config_rule
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ConfigRuleNames:
    type: array
    description: "Specify one or more AWS Config rule names to filter the results by rule."
  ComplianceTypes:
    type: array
    description: "Filters the results by compliance. The allowed values are COMPLIANT, NON_COMPLIANT, and INSUFFICIENT_DATA."
  NextToken:
    type: string
    description: "The nextToken string returned on a previous page that you use to get the next page of results in a paginated response."