---
description: 
pack: aws_config
enabled: true
entry_point: run.py
name: describe_configuration_recorders
runner_type: python-script
parameters:
  action:
    default: describe_configuration_recorders
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ConfigurationRecorderNames:
    type: array
    description: "A list of configuration recorder names."