---
description: 
pack: aws_config
enabled: true
entry_point: run.py
name: get_compliance_details_by_config_rule
runner_type: python-script
parameters:
  action:
    default: get_compliance_details_by_config_rule
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ConfigRuleName:
    type: string
    description: "The name of the AWS Config rule for which you want compliance information."
    required: true
  ComplianceTypes:
    type: array
    description: "Filters the results by compliance. The allowed values are COMPLIANT, NON_COMPLIANT, and NOT_APPLICABLE."
  Limit:
    type: integer
    description: "The maximum number of evaluation results returned on each page. The default is 10. You cannot specify a limit greater than 100. If you specify 0, AWS Config uses the default."
  NextToken:
    type: string
    description: "The nextToken string returned on a previous page that you use to get the next page of results in a paginated response."