---
name: produce
runner_type: python-script
description: "Send message to Apache Kafka broker system."
entry_point: produce.py
enabled: true
parameters:
  topic:
    description: "Kafka Topic to publish the message on."
    type: string
    required: true
  message:
    description: "The message to produce."
    type: string
    required: true
  hosts:
    description: "Kafka hostname(s) to connect in host:port format. Comma-separated for several hosts."
    type: string
