---
name: parse_message
pack: kafka
description: "Rule to test Kafka Sensor"
enabled: false

trigger:
  type: "kafka.new_message"
  parameters: {}

criteria:
  trigger.topic:
    type: "equals"
    pattern: "test"
  trigger.message.command:
    type: "equals"
    pattern: "MONITOR"

action:
  ref: core.local
  parameters:
    cmd: "echo {{ trigger.message.attributes[0].attributeName }}: {{ trigger.message.attributes[0].attributeValue }}"
