---
description: 
pack: aws_elasticbeanstalk
enabled: true
entry_point: run.py
name: abort_environment_update
runner_type: python-script
parameters:
  action:
    default: abort_environment_update
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  EnvironmentId:
    type: string
    description: "This specifies the ID of the environment with the in-progress update that you want to cancel."
  EnvironmentName:
    type: string
    description: "This specifies the name of the environment with the in-progress update that you want to cancel."