---
description: 
pack: aws_elasticbeanstalk
enabled: true
entry_point: run.py
name: apply_environment_managed_action
runner_type: python-script
parameters:
  action:
    default: apply_environment_managed_action
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ActionId:
    type: string
    description: "The action ID of the scheduled managed action to execute."
    required: true
  EnvironmentName:
    type: string
    description: "The name of the target environment."
  EnvironmentId:
    type: string
    description: "The environment ID of the target environment."