---
description: 
pack: aws_elasticbeanstalk
enabled: true
entry_point: run.py
name: describe_applications
runner_type: python-script
parameters:
  action:
    default: describe_applications
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationNames:
    type: array
    description: "If specified, AWS Elastic Beanstalk restricts the returned descriptions to only include those with the specified names. "