---
description: 
pack: aws_elasticbeanstalk
enabled: true
entry_point: run.py
name: describe_application_versions
runner_type: python-script
parameters:
  action:
    default: describe_application_versions
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "If specified, AWS Elastic Beanstalk restricts the returned descriptions to only include ones that are associated with the specified application."
  VersionLabels:
    type: array
    description: "If specified, restricts the returned descriptions to only include ones that have the specified version labels."