---
description: 
pack: aws_elasticbeanstalk
enabled: true
entry_point: run.py
name: describe_configuration_settings
runner_type: python-script
parameters:
  action:
    default: describe_configuration_settings
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: " The application for the environment or configuration template. "
    required: true
  TemplateName:
    type: string
    description: " The name of the configuration template to describe.   Conditional: You must specify either this parameter or an EnvironmentName, but not both. If you specify both, AWS Elastic Beanstalk returns an InvalidParameterCombination error. If you do not specify either, AWS Elastic Beanstalk returns a MissingRequiredParameter error. "
  EnvironmentName:
    type: string
    description: " The name of the environment to describe.   Condition: You must specify either this or a TemplateName, but not both. If you specify both, AWS Elastic Beanstalk returns an InvalidParameterCombination error. If you do not specify either, AWS Elastic Beanstalk returns MissingRequiredParameter error. "