---
description: 
pack: aws_elasticbeanstalk
enabled: true
entry_point: run.py
name: describe_environment_resources
runner_type: python-script
parameters:
  action:
    default: describe_environment_resources
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  EnvironmentId:
    type: string
    description: " The ID of the environment to retrieve AWS resource usage data.   Condition: You must specify either this or an EnvironmentName, or both. If you do not specify either, AWS Elastic Beanstalk returns MissingRequiredParameter error. "
  EnvironmentName:
    type: string
    description: " The name of the environment to retrieve AWS resource usage data.   Condition: You must specify either this or an EnvironmentId, or both. If you do not specify either, AWS Elastic Beanstalk returns MissingRequiredParameter error. "