---
description: 
pack: aws_elasticbeanstalk
enabled: true
entry_point: run.py
name: retrieve_environment_info
runner_type: python-script
parameters:
  action:
    default: retrieve_environment_info
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  InfoType:
    type: string
    description: " The type of information to retrieve. "
    required: true
  EnvironmentId:
    type: string
    description: "The ID of the data's environment. If no such environment is found, returns an InvalidParameterValue error. Condition: You must specify either this or an EnvironmentName, or both. If you do not specify either, AWS Elastic Beanstalk returns MissingRequiredParameter error."
  EnvironmentName:
    type: string
    description: "The name of the data's environment.  If no such environment is found, returns an InvalidParameterValue error.   Condition: You must specify either this or an EnvironmentId, or both. If you do not specify either, AWS Elastic Beanstalk returns MissingRequiredParameter error. "