---
description: 
pack: aws_elasticbeanstalk
enabled: true
entry_point: run.py
name: update_application_version
runner_type: python-script
parameters:
  action:
    default: update_application_version
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: " The name of the application associated with this version.   If no application is found with this name, UpdateApplication returns an InvalidParameterValue error. "
    required: true
  VersionLabel:
    type: string
    description: "The name of the version to update.  If no application version is found with this label, UpdateApplication returns an InvalidParameterValue error. "
    required: true
  Description:
    type: string
    description: "A new description for this release."