---
description: 
pack: aws_elasticbeanstalk
enabled: true
entry_point: run.py
name: update_configuration_template
runner_type: python-script
parameters:
  action:
    default: update_configuration_template
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "The name of the application associated with the configuration template to update.  If no application is found with this name, UpdateConfigurationTemplate returns an InvalidParameterValue error. "
    required: true
  TemplateName:
    type: string
    description: "The name of the configuration template to update.  If no configuration template is found with this name, UpdateConfigurationTemplate returns an InvalidParameterValue error. "
    required: true
  Description:
    type: string
    description: "A new description for the configuration."
  OptionSettings:
    type: array
    description: " A list of configuration option settings to update with the new specified option value. "
  OptionsToRemove:
    type: array
    description: " A list of configuration options to remove from the configuration set.   Constraint: You can remove only UserDefined configuration options. "