---
description: 
pack: aws_opsworks
enabled: true
entry_point: run.py
name: describe_deployments
runner_type: python-script
parameters:
  action:
    default: describe_deployments
    immutable: true
    type: string
  cls:
    default: opsworks
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  StackId:
    type: string
    description: "The stack ID. If you include this parameter, DescribeDeployments returns a description of the commands associated with the specified stack."
  AppId:
    type: string
    description: "The app ID. If you include this parameter, DescribeDeployments returns a description of the commands associated with the specified app."
  DeploymentIds:
    type: array
    description: "An array of deployment IDs to be described. If you include this parameter, DescribeDeployments returns a description of the specified deployments. Otherwise, it returns a description of every deployment."