---
name: "mongo-logs-2-splunk"
description: "Get mongo logs and send to splunk."
enabled: false

trigger:
  type: "core.st2.IntervalTimer"
  parameters:
    delta: 5
    unit: minutes

action:
  ref: "morpheus.mongo-logs-2-splunk"
