---
description: 
pack: aws_codedeploy
enabled: true
entry_point: run.py
name: batch_get_deployment_groups
runner_type: python-script
parameters:
  action:
    default: batch_get_deployment_groups
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  applicationName:
    type: string
    description: "The name of an AWS CodeDeploy application associated with the applicable IAM user or AWS account."
    required: true
  deploymentGroupNames:
    type: array
    description: "The deployment groups' names."
    required: true