---
description: 
pack: aws_codedeploy
enabled: true
entry_point: run.py
name: batch_get_applications
runner_type: python-script
parameters:
  action:
    default: batch_get_applications
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  applicationNames:
    type: array
    description: "A list of application names separated by spaces."