---
description: 
pack: aws_codedeploy
enabled: true
entry_point: run.py
name: batch_get_deployment_instances
runner_type: python-script
parameters:
  action:
    default: batch_get_deployment_instances
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  deploymentId:
    type: string
    description: "The unique ID of a deployment."
    required: true
  instanceIds:
    type: array
    description: "The unique IDs of instances in the deployment group."
    required: true