---
description: 
pack: aws_codedeploy
enabled: true
entry_point: run.py
name: delete_deployment_config
runner_type: python-script
parameters:
  action:
    default: delete_deployment_config
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  deploymentConfigName:
    type: string
    description: "The name of a deployment configuration associated with the applicable IAM user or AWS account."
    required: true