---
description: 
pack: aws_codedeploy
enabled: true
entry_point: run.py
name: get_deployment
runner_type: python-script
parameters:
  action:
    default: get_deployment
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  deploymentId:
    type: string
    description: "A deployment ID associated with the applicable IAM user or AWS account."
    required: true