---
description: 
pack: aws_codedeploy
enabled: true
entry_point: run.py
name: get_deployment_instance
runner_type: python-script
parameters:
  action:
    default: get_deployment_instance
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  deploymentId:
    type: string
    description: "The unique ID of a deployment."
    required: true
  instanceId:
    type: string
    description: "The unique ID of an instance in the deployment group."
    required: true