---
description: 
pack: aws_codedeploy
enabled: true
entry_point: run.py
name: list_application_revisions
runner_type: python-script
parameters:
  action:
    default: list_application_revisions
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  applicationName:
    type: string
    description: "The name of an AWS CodeDeploy application associated with the applicable IAM user or AWS account."
    required: true
  sortBy:
    type: string
    description: "The column name to use to sort the list results:  registerTime: Sort by the time the revisions were registered with AWS CodeDeploy. firstUsedTime: Sort by the time the revisions were first used in a deployment. lastUsedTime: Sort by the time the revisions were last used in a deployment.  If not specified or set to null, the results will be returned in an arbitrary order."
  sortOrder:
    type: string
    description: "The order in which to sort the list results:  ascending: ascending order. descending: descending order.  If not specified, the results will be sorted in ascending order. If set to null, the results will be sorted in an arbitrary order."
  s3Bucket:
    type: string
    description: "An Amazon S3 bucket name to limit the search for revisions. If set to null, all of the user's buckets will be searched."
  s3KeyPrefix:
    type: string
    description: "A key prefix for the set of Amazon S3 objects to limit the search for revisions."
  deployed:
    type: string
    description: "Whether to list revisions based on whether the revision is the target revision of an deployment group:  include: List revisions that are target revisions of a deployment group. exclude: Do not list revisions that are target revisions of a deployment group. ignore: List all revisions. "
  nextToken:
    type: string
    description: "An identifier returned from the previous list application revisions call. It can be used to return the next set of applications in the list."