---
description: 
pack: aws_codedeploy
enabled: true
entry_point: run.py
name: list_deployment_configs
runner_type: python-script
parameters:
  action:
    default: list_deployment_configs
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  nextToken:
    type: string
    description: "An identifier returned from the previous list deployment configurations call. It can be used to return the next set of deployment configurations in the list. "