---
description: 
pack: aws_codedeploy
enabled: true
entry_point: run.py
name: register_application_revision
runner_type: python-script
parameters:
  action:
    default: register_application_revision
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  applicationName:
    type: string
    description: "The name of an AWS CodeDeploy application associated with the applicable IAM user or AWS account."
    required: true
  revision:
    type: object
    description: "Information about the application revision to register, including type and location."
    required: true
  description:
    type: string
    description: "A comment about the revision."