---
description: 
pack: aws_codedeploy
enabled: true
entry_point: run.py
name: stop_deployment
runner_type: python-script
parameters:
  action:
    default: stop_deployment
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  deploymentId:
    type: string
    description: "The unique ID of a deployment."
    required: true