---
description: 
pack: aws_codedeploy
enabled: true
entry_point: run.py
name: update_application
runner_type: python-script
parameters:
  action:
    default: update_application
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  applicationName:
    type: string
    description: "The current name of the application you want to change."
  newApplicationName:
    type: string
    description: "The new name to give the application."