---
description: 
pack: aws_lambda
enabled: true
entry_point: run.py
name: update_function_configuration
runner_type: python-script
parameters:
  action:
    default: update_function_configuration
    immutable: true
    type: string
  cls:
    default: lambda
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  FunctionName:
    type: string
    description: "The name of the Lambda function.  You can specify a function name (for example, Thumbnail) or you can specify Amazon Resource Name (ARN) of the function (for example, arn:aws:lambda:us-west-2:account-id:function:ThumbNail). AWS Lambda also allows you to specify a partial ARN (for example, account-id:Thumbnail). Note that the length constraint applies only to the ARN. If you specify only the function name, it is limited to 64 character in length. "
    required: true
  Role:
    type: string
    description: "The Amazon Resource Name (ARN) of the IAM role that Lambda will assume when it executes your function. "
  Handler:
    type: string
    description: "The function that Lambda calls to begin executing your function. For Node.js, it is the module-name.export value in your function. "
  Description:
    type: string
    description: "A short user-defined function description. AWS Lambda does not use this value. Assign a meaningful description as you see fit."
  Timeout:
    type: integer
    description: "The function execution time at which AWS Lambda should terminate the function. Because the execution time has cost implications, we recommend you set this value based on your expected execution time. The default is 3 seconds. "
  MemorySize:
    type: integer
    description: "The amount of memory, in MB, your Lambda function is given. AWS Lambda uses this memory size to infer the amount of CPU allocated to your function. Your function use-case determines your CPU and memory requirements. For example, a database operation might need less memory compared to an image processing function. The default value is 128 MB. The value must be a multiple of 64 MB."
  VpcConfig:
    type: object
    description: ""
  Runtime:
    type: string
    description: ""