name: Add Pack Maintainers

on:
  issue_comment:
    types: created

jobs:
  tsc_membership_check:
    # "!add pack maintainers ..." comment on pull requests
    if: startsWith(github.event.comment.body, '!add pack maintainers') && github.event.issue.pull_request

    runs-on: ubuntu-latest
    steps:
      - name: Validate commentor permissions
        # must be a TSC member

  repo_is_ready_check:
    needs: [tsc_membership_check]
    runs-on: ubuntu-latest
    steps:
      - name: Make sure incubator PR is approved
      - name: Make sure pack repo is bootstrapped

      - name: Publish status in incubator PR comment # and/or label

  bootstrap_pack_repo:
    needs: [tsc_membership_check, repo_is_ready_check]
    runs-on: ubuntu-latest
    steps:
      - name: Parse comment to get maintainer details
        # output needs-team

      - name: Add team
        if: needs-team
      - name: Add maintainers to team
        if: needs-team
      - name: Add team to repo
        if: needs-team

      - name: Add maintainers to repo
        if: ! needs-team

      - name: Publish status in incubator PR comment # and/or label
