---
description: 
pack: aws_cloudfront
enabled: true
entry_point: run.py
name: get_distribution_config
runner_type: python-script
parameters:
  action:
    default: get_distribution_config
    immutable: true
    type: string
  cls:
    default: cloudfront
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Id:
    type: string
    description: "The distribution's id."
    required: true